mh_newsletter_home:
    path:     /
    defaults: { _controller: MHNewsletterBundle:Newsletter:index }

mh_newsletter_create:
    path:     /creation
    defaults: { _controller: MHNewsletterBundle:Newsletter:create }

mh_newsletter_view:
    path:     /view/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:view
    requirements:
            id:   \d+

mh_newsletter_edit:
    path:     /edit/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:edit
    requirements:
            id:   \d+

mh_newsletter_get:
    path:     /editget/
    defaults:
        _controller: MHNewsletterBundle:Newsletter:get

mh_newsletter_delete:
    path:     /delete/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:delete
    requirements:
            id:   \d+

mh_newsletter_rubrique_add:
    path:     /rubrique/add/{id}
    defaults:
        _controller: MHNewsletterBundle:Rubrique:add
    requirements:
            id:   \d+
mh_newsletter_rubrique_edit:
    path:     /rubrique/edit/{id}/{newsletter_id}
    defaults:
        _controller: MHNewsletterBundle:Rubrique:edit
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_rubrique_delete:
    path:     /rubrique/delete/{id}/{newsletter_id}
    defaults:
        _controller: MHNewsletterBundle:Rubrique:delete
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_post_add:
    path:     /post/add/{id}/{newsletter_id}
    defaults:
        _controller: MHNewsletterBundle:Post:add
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_post_edit:
    path:     /post/edit/{id}/{newsletter_id}
    defaults:
        _controller: MHNewsletterBundle:Post:edit
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_post_delete:
    path:     /rubrique/delete/{id}/{newsletter_id}/{rubrique_id}
    defaults:
        _controller: MHNewsletterBundle:Post:delete
    requirements:
            id:   \d+
            newsletter_id:   \d+
            rubrique_id:   \d+