mh_newsletter_home:
    path:     /
    defaults: { _controller: MHNewsletterBundle:Newsletter:index }

mh_newsletter_create:
    path:     /creation
    defaults: { _controller: MHNewsletterBundle:Newsletter:create }

mh_newsletter_view:
    path:     /view/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:view
    requirements:
            id:   \d+

mh_newsletter_download:
    path:     /download/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:download
    requirements:
            id:   \d+

mh_newsletter_edit:
    path:     /edit/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:edit
    requirements:
            id:   \d+

mh_newsletter_order:
    path:     /order
    defaults:
        _controller: MHNewsletterBundle:Newsletter:order

mh_newsletter_mail:
    path:     /mail/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:mail
    requirements:
            id:   \d+

mh_newsletter_edit_header:
    path:     /edit/{id}/header/
    defaults:
        _controller: MHNewsletterBundle:Newsletter:editheader
    requirements:
            id:   \d+

mh_newsletter_get:
    path:     /editget/
    defaults:
        _controller: MHNewsletterBundle:Newsletter:get

mh_newsletter_delete:
    path:     /delete/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:delete
    requirements:
            id:   \d+

mh_newsletter_copy:
    path:     /copy/{id}
    defaults:
        _controller: MHNewsletterBundle:Newsletter:copy
    requirements:
            id:   \d+

mh_newsletter_rubrique_add:
    path:     /{id}/rubrique/add
    defaults:
        _controller: MHNewsletterBundle:Rubrique:add
    requirements:
            id:   \d+
mh_newsletter_rubrique_edit:
    path:     /{newsletter_id}/rubrique/edit/{id}
    defaults:
        _controller: MHNewsletterBundle:Rubrique:edit
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_rubrique_delete:
    path:     /{newsletter_id}/rubrique/delete/{id}
    defaults:
        _controller: MHNewsletterBundle:Rubrique:delete
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_rubrique_order:
    path:     /rubrique/order
    defaults:
        _controller: MHNewsletterBundle:Rubrique:order

mh_newsletter_post_add:
    path:     /{newsletter_id}/rubrique/{id}/post/add
    defaults:
        _controller: MHNewsletterBundle:Post:add
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_post_order:
    path:     /post/order
    defaults:
        _controller: MHNewsletterBundle:Post:order

mh_newsletter_post_edit:
    path:     /{newsletter_id}/rubrique/post/edit/{id}
    defaults:
        _controller: MHNewsletterBundle:Post:edit
    requirements:
            id:   \d+
            newsletter_id:   \d+

mh_newsletter_post_delete:
    path:     /{newsletter_id}/rubrique/{rubrique_id}/delete/{id}
    defaults:
        _controller: MHNewsletterBundle:Post:delete
    requirements:
            id:   \d+
            newsletter_id:   \d+
            rubrique_id:   \d+