imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

easy_admin:
    entities:
        - MH\MailBundle\Entity\Mail
        - MH\MailBundle\Entity\User
        - MH\MailBundle\Entity\Post
        - MH\MailBundle\Entity\PostType
        - MH\MailBundle\Entity\Post\Agenda
        - MH\MailBundle\Entity\Post\Bloc
        - MH\MailBundle\Entity\Post\BlocTexteImage
        - MH\MailBundle\Entity\Post\Footer
        - MH\MailBundle\Entity\Post\Header
        - MH\MailBundle\Entity\Post\Texte
        - MH\MailBundle\Entity\Tool\Couleur
        - MH\MailBundle\Entity\Tool\Image
        - MH\MailBundle\Entity\Tool\Lien
        - MH\MailBundle\Entity\Tool\Paragraphe
        - MH\MailBundle\Entity\Tool\Police
        - MH\MailBundle\Entity\Tool\Texte
