root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /newsletter
        permanent: true

mh_newsletter:
    resource: "@MHNewsletterBundle/Resources/config/routing.yml"
    prefix:   /newsletter

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
