security:
    encoders:
        MH\NewsletterBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
         main:
              id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|admin)|css|images|js)/
            security: false

        main:
              pattern:      ^/
              anonymous:    true
              provider:     main
              form_login:
                  login_path: fos_user_security_login
                  check_path: fos_user_security_check
              logout:
                  path:       fos_user_security_logout
                  target:     fos_user_security_login
    access_control:
         - { path: ^/newsletter/edit, role: ROLE_ADMIN }
         - { path: ^/newsletter/order, role: ROLE_ADMIN }
         - { path: ^/newsletter/view, role: ROLE_ADMIN }
         - { path: ^/newsletter/delete, role: ROLE_ADMIN }
         - { path: ^/newsletter/copy, role: ROLE_ADMIN }
         - { path: ^/newsletter/mail, role: ROLE_ADMIN }
         - { path: ^/newsletter/add, role: ROLE_ADMIN }
         - { path: ^/newsletter/download, role: ROLE_ADMIN }
         - { path: ^/newsletter/creation, role: ROLE_ADMIN }
         - { path: /newsletter/, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/newsletter/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/newsletter/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/newsletter/profile, role: IS_AUTHENTICATED_ANONYMOUSLY }

