<?php

namespace MH\MailBundle\Repository;

/**
 * PostTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
