mh_mail_tool_home:
    path:     /
    defaults:
        _controller: MHMailBundle:Tool:index

mh_mail_couleur_add:
    path:     /couleur/add
    defaults:
        _controller: MHMailBundle:Tool:addCouleur

mh_mail_couleur_view:
    path:     /couleur/liste
    defaults:
        _controller: MHMailBundle:Tool:ViewCouleur

mh_mail_couleur_edit:
    path:     /couleur/edit/{id}
    defaults:
        _controller: MHMailBundle:Tool:editCouleur
    requirements:
                id:   \d+

mh_mail_couleur_delete:
    path:     /couleur/delete/{id}
    defaults:
        _controller: MHMailBundle:Tool:deleteCouleur
    requirements:
                id:   \d+

mh_mail_police_add:
    path:     /police/add
    defaults:
        _controller: MHMailBundle:Tool:addPolice

mh_mail_police_view:
    path:     /police/liste
    defaults:
        _controller: MHMailBundle:Tool:ViewPolice

mh_mail_police_edit:
    path:     /police/edit/{id}
    defaults:
        _controller: MHMailBundle:Tool:editPolice
    requirements:
                id:   \d+

mh_mail_police_delete:
    path:     /police/delete/{id}
    defaults:
        _controller: MHMailBundle:Tool:deletePolice
    requirements:
                id:   \d+

mh_mail_image_add:
    path:     /image/add
    defaults:
        _controller: MHMailBundle:Tool:addImage

mh_mail_image_view:
    path:     /image/liste
    defaults:
        _controller: MHMailBundle:Tool:ViewImage

mh_mail_image_edit:
    path:     /image/edit/{id}
    defaults:
        _controller: MHMailBundle:Tool:editImage
    requirements:
                id:   \d+

mh_mail_image_delete:
    path:     /image/delete/{id}
    defaults:
        _controller: MHMailBundle:Tool:deleteImage
    requirements:
                id:   \d+
