mh_mail_home:
    path:     /
    defaults: { _controller: MHMailBundle:Mail:index }

mh_mail_create:
    path:     /creation
    defaults: { _controller: MHMailBundle:Mail:create }

mh_mail_view:
    path:     /view/{id}
    defaults:
        _controller: MHMailBundle:Mail:view
    requirements:
            id:   \d+

mh_mail_edit:
    path:     /edit/{id}
    defaults:
        _controller: MHMailBundle:Mail:edit
    requirements:
            id:   \d+
mh_mail_edit_header:
    path:     /edit/header/{id}
    defaults:
        _controller: MHMailBundle:Mail:editheader
    requirements:
            id:   \d+

mh_mail_copy:
    path:     /copy/{id}
    defaults:
        _controller: MHMailBundle:Mail:copy
    requirements:
            id:   \d+

mh_mail_delete:
    path:     /delete/{id}
    defaults:
        _controller: MHMailBundle:Mail:delete
    requirements:
            id:   \d+

mh_mail_mail:
    path:     /mail/{id}
    defaults:
        _controller: MHMailBundle:Mail:mail
    requirements:
            id:   \d+

mh_mail_order:
    path:     /order
    defaults:
        _controller: MHMailBundle:Mail:order



mh_mail_post_add:
    path:     /post/add/{id}
    defaults:
        _controller: MHMailBundle:Post:add
    requirements:
            id:   \d+
mh_mail_post_edit:
    path:     /post/edit/{id}/{mail_id}
    defaults:
        _controller: MHMailBundle:Post:edit
    requirements:
            id:   \d+
            mail_id:   \d+

mh_mail_post_delete:
    path:     /post/delete/{id}/{mail_id}
    defaults:
        _controller: MHMailBundle:Post:delete
    requirements:
            id:   \d+
            mail_id:   \d+

mh_mail_post_order:
    path:     /post/order
    defaults:
        _controller: MHMailBundle:Post:order

mh_mail_post_select:
    path:     /post/select/{id}
    defaults:
        _controller: MHMailBundle:PostType:select
    requirements:
            id:   \d+

mh_mail_agenda_add:
    path:     /post/add/{id}/agenda
    defaults:
        _controller: MHMailBundle:Agenda:addAgenda
    requirements:
            id:   \d+

mh_mail_agenda_edit:
    path:     /post/edit/{id}/agenda
    defaults:
        _controller: MHMailBundle:Agenda:editAgenda
    requirements:
            id:   \d+

mh_mail_header_add:
    path:     /post/add/{id}/header
    defaults:
        _controller: MHMailBundle:Header/Header:addHeader
    requirements:
            id:   \d+

mh_mail_header_edit:
    path:     /post/edit/{id}/header
    defaults:
        _controller: MHMailBundle:Header/Header:editHeader
    requirements:
            id:   \d+

mh_mail_footer_admission_add:
    path:     /post/add/{id}/footer_admission
    defaults:
        _controller: MHMailBundle:Footer/Footer:addFooterAdmission
    requirements:
            id:   \d+

mh_mail_footer_admission_edit:
    path:     /post/edit/{id}/footer_admission
    defaults:
        _controller: MHMailBundle:Footer/Footer:editFooterAdmission
    requirements:
            id:   \d+

mh_mail_texte_separation_add:
    path:     /post/add/{id}/texte_separation
    defaults:
        _controller: MHMailBundle:Texte/Texte:addTexte
    requirements:
            id:   \d+

mh_mail_texte_separation_edit:
    path:     /post/edit/{id}/texte_separation
    defaults:
        _controller: MHMailBundle:Texte/Texte:editTexte
    requirements:
            id:   \d+