mh_mail_bloc_photo_texte_add:
    path:     /post/add/{id}/bloc/photo-texte
    defaults:
        _controller: MHMailBundle:Post\PhotoTexte:addBloc
    requirements:
            id:   \d+

mh_mail_bloc_photo_texte_edit:
    path:     /post/edit/{id}/bloc/photo-texte
    defaults:
        _controller: MHMailBundle:Post\PhotoTexte:editBloc
    requirements:
            id:   \d+