services:
#    mh_mail.example:
#        class: MH\MailBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
