<?php

namespace MH\MailBundle\Repository\Post;

/**
 * HeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderRepository extends \Doctrine\ORM\EntityRepository
{
}
