<?php

namespace MH\MailBundle\Repository\Tool;

/**
 * ParagrapheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParagrapheRepository extends \Doctrine\ORM\EntityRepository
{
}
